// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoConverter.Database;

#nullable disable

namespace VideoConverter.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241125191833_Temp")]
    partial class Temp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("VideoConverter.Models.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("VideoConverter.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VideoConverter.Models.Settings", b =>
                {
                    b.OwnsOne("VideoConverter.Models.Settings_FFmpeg", "FFmpeg", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FFmpegPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FFprobePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LogLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Mode")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Threads")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("VideoConverter.Models.Settings_Files", "Files", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("GroupByFolders")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.OwnsOne("VideoConverter.Models.Settings_MediaPlayer", "MediaPlayer", b1 =>
                        {
                            b1.Property<int>("SettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MediaPlayerPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Mode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });

                    b.Navigation("FFmpeg")
                        .IsRequired();

                    b.Navigation("Files")
                        .IsRequired();

                    b.Navigation("MediaPlayer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
