// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoConverter.Database;

#nullable disable

namespace VideoConverter.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241107190644_TEMP")]
    partial class TEMP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("VideoConverter.Models.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileItems");
                });

            modelBuilder.Entity("VideoConverter.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("VideoConverter.Models.Setting", b =>
                {
                    b.OwnsOne("VideoConverter.Models.FFmpeg", "FFmpeg", b1 =>
                        {
                            b1.Property<int>("SettingId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LogLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Mode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Threads")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingId");
                        });

                    b.OwnsOne("VideoConverter.Models.FilesList", "FilesList", b1 =>
                        {
                            b1.Property<int>("SettingId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("GroupFolders")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingId");
                        });

                    b.Navigation("FFmpeg")
                        .IsRequired();

                    b.Navigation("FilesList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
